### ISSUE TITLE
【Processing】FullScreen

### ISSUE THREAD

**Issue by soichiro-imamura** [036base/Processing#1]
FullScreenの問題で、画面解像度はWQHD 2560 x 1440なんだけど、解像度はFHD 1920 x 1080で画面サイズだけFullScreenってできないかな？

**Comment by soichiro-imamura** [comment]
【Processing】[なんでだろ？]画面サイズによって画像のスピードが変わる！
FullScreenにしなくても、プロパティ指定した場合にも画像サイズが大きいほうが遅くなる。

**Comment by masahiro-kawada** [comment]
FullScreenっていう概念だと難しいかもね。サブモニター側の解像度を1920 x 1080に設定してそっち側にFullScreenで表示したら、1920 x 1080になるんじゃないかな？

**Comment by masahiro-kawada** [comment]
サブモニター側の解像度を1920 x 1080にしてFullScreenにしたら、1920 x 1080の表示になるんじゃないかな。

**Comment by soichiro-imamura** [comment]
そうだね！それでやってみる

**Comment by soichiro-imamura** [comment]
グラフィックの指定はP2D！
これじゃないと速度も遅いし、動作が微妙。
