### ISSUE TITLE
【Eclipse】実行ファイル作成

### ISSUE THREAD

**Issue by soichiro-imamura** [036base/Processing#17]
Java Eclipseで実行可能なJARファイルを作成する
http://sunjava.seesaa.net/article/57546363.html

**Comment by masahiro-kawada** [comment]
JARファイルにしたときって設定ファイル（processing.properties）は外だしになった？

**Comment by soichiro-imamura** [comment]
やる前にあれだったからやってない。。。

**Comment by masahiro-kawada** [comment]
あ。。。申し訳ない。

**Comment by soichiro-imamura** [comment]
全然よいよ！

**Comment by soichiro-imamura** [comment]
単純に作成するとjarファイルのみ。
propertiesファイルを外出しにする方法でやらなければ。。。

**Comment by soichiro-imamura** [comment]
javaパッケージ化に含む為Close
