### ISSUE TITLE
【Processing】3Dバージョン

### ISSUE THREAD

**Issue by masahiro-kawada** [036base/Processing#21]
3Dアニメーション化

**Comment by masahiro-kawada** [comment]
３Ｄバージョンをコミットしました。
試す場合は「MainSketch3D」クラスを実行してください。
それっぽい動きになってると思う♪シャッフルぬりえみたいに滑らかではないけど。。。
詳しい仕様はおいおい。

**Comment by soichiro-imamura** [comment]
確認したよ！
３Ｄの動きはしてるけど、微妙かなｗｗ
スピードが早いからかな？ちょっとわかりにくい(๑-ิ느-ิ๑)
尻尾ヒラヒラはいいねー(◎´□`)ｻｲｺｫｫｫｰ☆

**Comment by masahiro-kawada** [comment]
動きが微妙ってなると、全面改修だな！
まぁ回遊的な動きができればいいんだけどね。。。
今はA座標からB座標に向かって移動って動き。

**Comment by soichiro-imamura** [comment]
いやいや！微妙っていうのは今の状態がってことだよ！
まだ世には出せないかなって意味(๑ʻัદʻั๑)
小慣れていけば全然イケるはず！！

**Comment by soichiro-imamura** [comment]
たぶんマシンスペックの問題かな？
僕のがスペックがいいからか超動きが早いんだよね！
普通のMainSketch.javaの方も早いから
				_speed = _animationSpeed + ceil(rand / 100);
から
				_speed = _animationSpeed + ceil(rand / 1000);
に変えてるもん！
今回はそれの調整が出来なかったから。。。

**Comment by masahiro-kawada** [comment]
そんな動き変わるんだ！
３Dは設定ファイルのスピードが反映されてないからね。
そこも含めいろいろ試してみます！

**Comment by soichiro-imamura** [comment]
動画撮って送るわ！！
ってか動画作成組み込めないかな？

**Comment by masahiro-kawada** [comment]
Processingで動画に落とせるっぽいんだけど実現できてない！
それも調べとく！

**Comment by soichiro-imamura** [comment]
うん！なんか画像を何枚も撮ってそれを繋げる感じかな！
僕もググッたんだけど、川田くんのほうが見たらすぐわかるかなと思って。

http://inter-arteq.com/2014/11/08/processing%E3%81%A7%E5%8B%95%E7%94%BB%E3%82%92%E6%9B%B8%E3%81%8D%E5%87%BA%E3%81%99%E6%96%B9%E6%B3%95/

**Comment by masahiro-kawada** [comment]
動画保存を実装してみたよ。
/output/readme.txt　に実行手順は書いてあります。
動画変換はffmpegってのを使ってるけど、動画の精度は
保存する画像の種類とかFrameRateの設定とかで違ってくるかも。
ffmpegに関しても勉強が必要だね。

**Comment by masahiro-kawada** [comment]
速度なんだけど、処理的に到着座標に向かって
減速していくって感じだから、画面サイズが
大きいと距離が長くて速くなっちゃうと思う。
処理を見直さないとダメだね。
