### ISSUE TITLE
【出店】ポイントカード

### ISSUE THREAD

**Issue by soichiro-imamura** [036base/Processing#23]
ポイントカードを作る。
【用紙】
画用紙 or 名刺
【内容】
塗り絵１枚１ポイント
10ポイントで塗り絵１枚プレゼント

【ToDo】
①用紙買う
②デザイン
③スタンプ買う

**Comment by masahiro-kawada** [comment]
今って１枚２００円なんだっけ？
売上は落ちるかもしれないけど、１枚単価下げないと複数枚の購入とか同日リピーターは難しいんじゃないかと思う。同日なら２枚目からは半額とか。
映像になると言っても「ぬりえ」だからね。親からしたらそれに５枚で１０００円とかは出さないかも。

**Comment by soichiro-imamura** [comment]
そういう問題じゃないね！
まず「塗り絵」目的でマルシェに来てないから、
子供がしたいっていうからとりあえずやらせるけど親が早く次に行きたいって感じ。
気持ちはわからんでもない。

５枚ってのは元々思ってないよ！
意外だったってのは、２枚はいるかなと思ってたけどいなかったことかな！
子供のついでに親もやるってのはあったけど！

**Comment by soichiro-imamura** [comment]
>今って１枚２００円なんだっけ？
→うん！200円だよ！

**Comment by masahiro-kawada** [comment]
あぁそういうことね。
マルシェだとそうなっちゃうかもね！
いろいろ見てまわるって感じになるか。

**Comment by soichiro-imamura** [comment]
そうなのよねー！
今は修行＆宣伝の期間だと思ってるから、
マルシェとかでは儲けはとりあえずいいかな！！

パッケージ化して売りまくりたいね！！！

**Comment by soichiro-imamura** [comment]
通知こないから気付かなかったけど、ぬりえのイベント作ったら全然知らない人が「興味あり」押してた！
嬉しい！気合い入るわ！

**Comment by masahiro-kawada** [comment]
嬉しいね！３Dバージョンの感想も聞かせてね！

**Comment by soichiro-imamura** [comment]
了解です！まだ見れてないっす！今日確認します！
